### ISSUE TITLE
Delete states not working

### ISSUE THREAD

**Issue by startmyquest** [ahmedmigo/Symbol-state#1] opened 2017-10-05 15:40 UTC
I have set-up two states for two different symbols. When I select to set state I noticed however, that the dropdown includes all 4 states for both symbols in my options. Probably because I duplicated the first symbol in order to create the second.

I thought I would be able to delete the wrong states from the dropdown list, but selecting > Delete Symbol State and then one of the wrongly duplicated states, doesn't seem to do anything?

Love the plugin -great job.

**Comment by ahmedmigo** [comment] 2017-10-05 15:43
@startmyquest Hello thank you for feedback, 
I got the issue thank you for reporting it,
and I will fix it very soon 😉

**Comment by startmyquest** [comment] 2017-10-05 15:59
Ok. I've done a bit of testing. Looks like two different problems.

For delete states not working, I do the following:
1. Create symbol instance
2. Add a symbol state (state 1)
3. Change overrides
4. Add another symbol state (state 2)

5. Select an instance of the symbol
6. Go to plugin menu, select Delete Symbol State
6. From dropdown selecting either State 1 / State 2 (doesn't matter)
7. Click Remove button and dialog box closes, but...

8. If I go back to same symbol instance
9. Go to plugin menu, select Set Symbol State, the "removed" state is still in dropdown

I'll log the other problem in an different issue

**Comment by ahmedmigo** [comment] 2017-10-05 16:01
Great I got the problem and I will work solving it very soon

**Comment by ahmedmigo** [comment] 2017-10-05 20:57
Remove Feature is now fixed, Can you check it and tell me if it is working fine or not ?

**Comment by ahmedmigo** [comment] 2017-10-06 07:14
the issue is fixed in version 1.1

**Closed as completed** 2017-10-06 07:13 UTC
